server {
  listen 80;
  server_name localhost;

  # Set the root directory for static files
  root /usr/share/nginx/html;
  index index.html;

  location / {
    # Try to serve the requested file, then directory, otherwise fall back to index.html
    try_files $uri $uri/ /index.html;
  }

  location /api/ {
    rewrite /api/(.*) /$1 break;
    proxy_pass https://capstone-kiosk.onrender.com;
    proxy_set_header Host $host;
  }

  # Optional: Add headers to prevent caching issues
  location ~* \.(?:ico|css|js|gif|jpe?g|png)$ {
    expires 1y;
    add_header Cache-Control "public";
  }
}
